let APIS = {
	LOGIN_USER: "login",
	FORGOT_PASSWORD: "forgot-password",
	REGISTER: "register",
	SELLER_REGISTER: "startToSellRegister",
	VERIFY_OTP: "checkOtp",
	RESET_PASSWORD: "reset-password",
	COUNTRIES: "countries",
	SEND_MOBILE_OTP: "seller/company-register-send-otp",
	VERIFY_MOBILE_OTP: "seller/company-register-verify-otp",
	COMPANY_REGISTRATION: "seller/company-register",
	UPDATE_PASSWORD: "change-password",
	UPDATE_PROFILE: "update-profile",
	UPDATE_PROFILE_PICTURE: "update-profile-picture",
	SEND_INVITATION_LINK: "/seller/send-invitation",
	SELLER_COMPANY_LIST: "seller/company-list",
	GET_ADDRESSES: "list-address",
	SAVE_ADDRESS: "add-address",
	UPDATE_ADDRESS: "edit-address",
	DELETE_ADDRESS: "delete-address",
	GET_BLOGS: "blog-list",
	GET_BLOG_DETAILS: "blog-details/:id",
	SUBSCRIBE_NEWSLETTER: "new-subscribe",
	GET_CMS_PAGE: "cms-page",
	GET_PACKAGE: "package/list",
	SET_DEFAULT_COMPANY: "/seller/change-default-company/",
	GET_UNIT_TYPES: "unit-types",
	CREATE_PRODUCT: "seller/product/add",
	UPDATE_PRODUCT: "seller/product/update",
	GET_PRODUCT: "product/details",
	GET_PRODUCT_INVENTORY: "seller/product/inventory/get",
	SET_DEFAULT_PRODUCT_IMAGE: "product/set-default-image",
	DELETE_PRODUCT_IMAGE: "product/delete-image",
	CATEGORY_FIELD_LIST: "seller/category/get-product-fields",
	CATEGORY: "category/category-list",
	CATEGORY_DETAIL: "category-detail",
	HOME_RECENT_VIEW: "home/recently-views",
	HOME_CATEGORY_PRODUCT: "home/category-product-list",
	PAGE_CATEGORY_DATA: "category/products-and-popular-category",
	PAGE_CATEGORY_RECOMANDED_DATA: "category/recommended-products",
	CATEGORIES_LIST: "category/category-list",
	CATEGORIES_LIST_ALL: "category/category-list",
	PRODUCT_SEARCH: "product/search",
	TRENDING_CATEGORIES: "trending-categories",
	PRODUCT_SEARCH_PAGE: "product/product-list-by-filter",
	PRODUCT_SEARCH_FOR_SEARCH_BAR: "product/search-bar-product-list",
	SELLER_CATEGORY_DETAIL: "category/detail/",
	SELLER_CATEGORIES_LIST_ALL: "category/all-list",
	SELLER_CATEGORIES_LIST: "category/list",
	SELLER_CATEGORY_FIELD_LIST: "seller/category/get-product-fields",
	CHECKOUT_PRODUCTS: "checkout/create",
	CHECKOUT: "checkout",
	ADD_EDIT_REVIEW: "review/create",
	GET_PRODUCT_REVIEW: "product/review",
	GET_SUPPORTED_CURRENCY: "supported-currency",
	ADD_FAVOURITE: "favourite/create",
	DELETE_FAVOURITE: "favourite/delete",
	GET_FAVOURITE_LIST: "favourite/list",

	BUYER_ORDER_LIST: "order/list",

	PRODUCT_LIST: "seller/product/list",
	PRODUCT_CREATE: "seller/product/add",
	PRODUCT_UPDATE: "seller/product/update",
	PRODUCT_DELETE_IMAGE: "seller/product/delete-image/",
	PRODUCT_SET_DEFAULT: "seller/product/set-default-image",
	PRODUCT_DETAIL: "seller/product/detail",

	SELLER_ORDER_LIST: "seller/order/list",
	SELLER_CUSTOMER_LIST: "seller/customer-list",

	COMPANY_OVERVIEW: "seller/company/update-overview",
	COMPANY_PRODUCT_QAULITY_CONTROL: "seller/company/update-quality-control",
	COMPANY_PRODUCTION_CAPACITY: "seller/company/update-production-capacity",
	COMPANY_OVERVIEW_DELETE_IMAGE: "seller/company/delete-overview-image",
	GET_COMPANY_DETAILS: "seller/company/get-additional-details",
	DELETE_COMPANY_DETAILS: "seller/company/delete-company",

	ADMIN_LOGIN: "super-admin/login",
	ADMIN_USER_PERMISSION: "super-admin/user/permission",
	ADMIN_FORGOT_PASSWORD: "super-admin/forgot-password",
	ADMIN_RESET_PASSWORD: "super-admin/reset-password",
	ADMIN_UPDATE_PASSWORD: "super-admin/change-password",
	ADMIN_VERIFY_OTP: "super-admin/checkOtp",
	ADMIN_MEDIA: "super-admin/media-list",
	ADMIN_MEDIA_UPLOAD: "super-admin/media-create",
	ADMIN_MEDIA_DELETE: "super-admin/media-delete",
	ADMIN_UPDATE_PROFILE: "super-admin/update-profile",
	ADMIN_UPDATE_PROFILE_PICTURE: "super-admin/update-profile-picture",
	ADMIN_BUYERS_LIST: "super-admin/buyer/list",
	ADMIN_BUYER_CREATE: "super-admin/buyer/create",
	ADMIN_BUYER_UPDATE: "super-admin/buyer/edit",
	ADMIN_BUYER_UPDATE_STATUS: "super-admin/buyer/changeStatus",
	ADMIN_CMS_PAGES: "super-admin/cms-pages",
	ADMIN_SELLERS_LIST: "super-admin/seller/list",
	ADMIN_SELLER_UPDATE: "super-admin/seller/edit",
	ADMIN_COMPANIES_LIST: "super-admin/company/list",
	ADMIN_COMPANIE_BY_ID: "super-admin/company/detail/",
	ADMIN_COMPANY_VERIFY: "super-admin/company/verify",
	ADMIN_COMPANY_CREATE: "super-admin/company/create",
	ADMIN_COMPANY_DELETE: "super-admin/company/delete-company",
	ADMIN_COMPANY_EDIT: "super-admin/company/edit",
	ADMIN_BLOGS_LIST: "super-admin/blog/list",
	ADMIN_BLOG_CREATE: "super-admin/blog/create",
	ADMIN_BLOG_UPDATE: "super-admin/blog/edit",
	ADMIN_BLOG_DELETE: "super-admin/blog/delete",

	ADMIN_ORDER_LIST: "super-admin/order/list",

	ADMIN_QUESTION_LIST: "super-admin/question/list",
	ADMIN_QUESTION_DELETE: "super-admin/question/delete",
	ADMIN_QUESTION_UPDATE: "super-admin/question/create",
	ADMIN_QUESTION_CREATE: "super-admin/question/create",

	ADMIN_PRODUCT_LIST: "super-admin/product/list",
	ADMIN_PRODUCT_CREATE: "super-admin/product/add",
	ADMIN_PRODUCT_UPDATE: "super-admin/product/update",
	ADMIN_PRODUCT_DELETE_IMAGE: "super-admin/product/delete-image/",
	ADMIN_PRODUCT_SET_DEFAULT: "super-admin/product/set-default-image",
	ADMIN_PRODUCT_DETAIL: "super-admin/product/detail",
	ADMIN_GET_PRODUCT_INVENTORY: "super-admin/product/inventory/get",
	ADMIN_SAVE_PRODUCT_INVENTORY: "super-admin/product/inventory/manage",

	ADMIN_PERMISSION: "super-admin/permission",
	ADMIN_ROLES: "super-admin/roles",
	ADMIN_UPDATE_CREATE_ROLE: "super-admin/create-update-role",
	ADMIN_REMOVE_ROLE: "super-admin/remove-role",
	ADMIN_SUBSCRIBERS_LIST: "super-admin/subscribe-list",
	ADMIN_REMOVE_SUBSCRIBER: "super-admin/delete-subscribe",
	ADMIN_GET: "super-admin/admin/list",
	ADMIN_CREATE: "super-admin/admin/create",
	ADMIN_UPDATE: "super-admin/admin/edit",
	ADMIN_DELETE: "super-admin/admin/delete",
	ADMIN_ASSIGN_ROLE: " super-admin/role/assign",
	ADMIN_CMS_UPLOAD_IMAGE: "super-admin/cms-page/upload-image",
	ADMIN_CMS_ITEM_REMOVE: "super-admin/cms-page/item-remove",
	ADMIN_CMS_PAGE_UPDATE: "super-admin/cms-page/update",

	ADMIN_PACKAGE_LIST: "super-admin/package/list",
	ADMIN_PACKAGE_UPDATE: "super-admin/package/edit",
	ADMIN_CATEGORIES_LIST: "super-admin/category/list",
	ADMIN_CATEGORIES_LIST_ALL: "super-admin/category/all-list",
	ADMIN_CATEGORY_UPDATE: "super-admin/category/edit",
	ADMIN_CATEGORY_CREATE: "super-admin/category/create",
	ADMIN_CATEGORY_UPDATE_STATUS: "super-admin/category/changeStatus",
	ADMIN_CATEGORY_DELETE: "super-admin/category/delete",
	ADMIN_CATEGORY_FIELD_LIST: "super-admin/category/get-product-fields",
	ADMIN_CATEGORY_FIELD_DELETE: "super-admin/category/delete-product-fields",
	ADMIN_CATEGORY_FIELD_CREATE: "super-admin/category/add-product-fields",
	ADMIN_CATEGORY_DETAIL: "super-admin/category/detail/",

	GET_QUESTION_LIST: "question/list",
	SAVE_DISPUTE_PRODUCT: "dispute/create",
	GET_DISPUTE_LIST: "dispute/list",
	GET_CHAT_LIST: "get-chat-list",
	

	SELLER_PRODUCT_REVIEW: "seller/seller-product-review",
	SELLER_CHECKOUT_CREATE: "seller/checkout/create",
	SELLER_NOTIFICATION_CREATE: "seller/notification/create",
	SELLER_NOTIFICATION_LIST: "seller/notification/list",
	SUPER_ADMIN_NOTIFICATION_LIST: "super-admin/notification/list",
	SUPER_ADMIN_NOTIFICATION_CREATE: "super-admin/notification/create",
	CREATE_BUYER: "create_buyer",
	CREATE_SELLER: "create_seller",
	GET_SELLER: "get_seller",
	GET_BUYER: "get_buyer",
	SELLER_BANK_CONNECT_STATUS: "seller_bank_connect_status",
	BUYER_BANK_CONNECT_STATUS: "buyer_bank_connect_status",

	BUYER_ORDER_DETAIL: "order/detail/",
	SELLER_ORDER_DETAIL: "seller/order/details/",
	SUPER_ADMIN_ORDER_DETAIL: "super-admin/order/details/",

	ADMIN_BADGES_LIST: "super-admin/badge/list",
	ADMIN_BADGE_UPDATE: "super-admin/badge/update",
	GET_BADGES: "",
	GET_BADGE_DETAILS: "super-admin/badge/detail/",
	ADMIN_BADGE_CREATE: "super-admin/badge/create",
	ADMIN_BADGE_DELETE: "super-admin/badge/delete",

	GET_PRODUCT_REVIEWS: "product/review/",
	CREATE_PRODUCT_REVIEWS: "",
	DELETE_PRODUCT_REVIEW: "",
	UPDATE_PRODUCT_REVIEW: "",

	SELLER_GET_SINGLE_CATALOGUE: "seller/catalogue/detail/",
	SELLER_CREATE_CATALOGUE: "seller/catalogue/create",
	SELLER_UPDATE_CATALOGUE: "seller/catalogue/update",
	SELLER_LIST_CATALOGUE: "seller/catalogue/list",
	SELLER_DELETE_CATALOGUE: "seller/catalogue/delete/",

	SELLER_GET_SINGLE_BUSINESS_CARD: "seller/businesscard/detail/",
	SELLER_CREATE_BUSINESS_CARD: "seller/businesscard/create",
	SELLER_UPDATE_BUSINESS_CARD: "seller/businesscard/update",
	SELLER_LIST_BUSINESS_CARD: "seller/businesscard/list",
	SELLER_DELETE_BUSINESS_CARD: "seller/businesscard/delete/",

	ADMIN_BUYER_DETAILS: "super-admin/buyer/order-details/",
	ADMIN_COMPANY_DETAILS: "super-admin/company/order-details/",
	SELLER_SEARCH_BUYER_BY_MAIL: "seller/search-buyer",

	SAVE_PRODUCT_INVENTORY: "seller/product/inventory/manage",
	SUPER_ADMIN_GET_DETAILS: "super-admin/home/get-details",
	SELLER_GET_DETAILS: "seller/home/get-details",
	BUYER_GET_DETAILS: "buyer/home/get-details",

	PRODUCT_REVIEW_DETAILS: "seller/product/review/",
	ADMIN_PRODUCT_REVIEW_DETAILS: "super-admin/product/review/",
	//notifications admin
	SUPER_ADMIN_CREATE_NOTIFICATION: "super-admin/notification/create",
	SUPER_ADMIN_GET_NOTIFICATIONS: "super-admin/notification/list",
	SUPER_ADMIN_UPDATE_NOTIFICATION: "super-admin/notification/create",
	SUPER_ADMIN_DELETE_NOTIFICATION: "super-admin/notification/delete",
	///
	//notifications seller
	SELLER_CREATE_NOTIFICATION: "seller/notification/create",
	SELLER_GET_NOTIFICATIONS: "seller/notification/list",
	SELLER_UPDATE_NOTIFICATION: "seller/notification/create",
	SELLER_DELETE_NOTIFICATION: "seller/notification/delete/",
	SELLER_GET_ORDER_MASTER_STATUS: "get-order-master-status",
	SELLER_UPDATE_ORDER_STATUS: "seller/update-order-status",
	ADMIN_GET_ORDER_MASTER_STATUS: "super-admin/get-order-master-status",
	ADMIN_UPDATE_ORDER_STATUS: "super-admin/update-order-status",
	//campaign packages
	ADMIN_CREATE_CAMPAIGN_PACKAGE: "super-admin/package-campaign/add",
	ADMIN_GET_CAMPAIGN_PACKAGE: "super-admin/package-campaign/list",
	ADMIN_UPDATE_CAMPAIGN_PACKAGE: "super-admin/package-campaign/edit",
	ADMIN_DELETE_CAMPAIGN_PACKAGE: "super-admin/package-campaign/delete/",

	//seller promotions
	SELLER_CREATE_CAMPAIGN: "seller/campaign/add",
	SELLER_LIST_CAMPAIGN: "seller/campaign/list",
	SELLER_UPDATE_STATUS_CAMPAIGN: "seller/campaign/changeStatus",
	SELLER_GET_CAMPAIGN_PACKAGES: "seller/package-campaign/list",

	BUYER_ENQUIRE_QUATATION_CREATE: "enquire-quatation/create",
	BUYER_ENQUIRE_QUATATION_UPDATE: "enquire-quatation/update",
	BUYER_ENQUIRE_QUATATION_PRODUCT_LIST: "product/list",
	BUYER_ENQUIRE_QUATATION_LIST: "enquire-quatation/list",
	SELLER_ENQUIRE_QUATATION_LIST: "seller/enquire-quatation/list",
	SELLER_ENQUIRE_QUATATION_DETAILS: "seller/enquire-quatation/details/",

	READY_TO_SHIP: "products/ready-to-ship",
	TRENDING_PRODUCTS: "products/trending-products",
	BEST_PRODUCT: "best-product",
	NEW_ARRIVAL: "products/new-arrival",

	UPLOAD_FILE: "/upload-file",
};

export default APIS;
