export const CONSTANTS = {
  PERSIST_KEY: "DAMARKET_AUTH",
  PERSIST_KEY_CART_NEW: "DAMARKET_NEW_CART",
  PERSIST_LANGUAGE_KEY: "DAMARKET_LANGUAGE",
  PERSIST_CURRENCY_KEY: "DAMARKET_CURRENCY",
  PERSIST_ADMIN_KEY: "DAMARKET_ADMIN_AUTH",
  PERSIST_COMPANY: "DAMARKET_COMPANY",
  PERSIST_KEY_CART: "DAMARKET_CART",
  COMPANY_TYPES: [
    { label: "Public Company", value: "PUBLIC_COMPANY" },
    { label: "Public Treding Company", value: "PUBLIC_TRADE_COMPANY" },
    { label: "Private Company", value: "PRIVATE_COMPANY" },
    { label: "None. I'm Particuler", value: "PERSONAL" },
  ],
  CMS_PAGE: {
    VERIFIED_SUPLIER: "verified_suplier",
    TERM_CONDITION: "term-condition",
    PRIVACY_POLICY: "privacy-policy",
    SHIPPING_POLICY: "shipping-policy",
    PAY_SAFE: "pay-safe",
    ABOUT_US: "about-us",
    HELP: "help",
    MEMBERSHIP: "membership",
    HOME: "home",
    ACEDAMY: "acedamy",
    NOT_FOUND: "404",
    START_TO_SELL: "starttosell",
  },
  ADMIN_SEND_TO_TYPES: [
    { label: "BUYER", value: "BUYER" },
    { label: "SELLER", value: "SELLER" },
  ],
  SELLER_SEND_TO_TYPES: [{ label: "BUYER", value: "BUYER" }],
  NOTIFICATION_SEND_TYPES: [
    { label: "EMAIL", value: "EMAIL" },
    { label: "MESSAGE", value: "MESSAGE" },
  ],
  PACKAGE_MONTHS: [
    { label: "1 Month", value: 1 },
    { label: "2 Months", value: 2 },
    { label: "3 Months", value: 3 },
    { label: "4 Months", value: 4 },
    { label: "5 Months", value: 5 },
    { label: "6 Months", value: 6 },
    { label: "7 Months", value: 7 },
    { label: "8 Months", value: 8 },
    { label: "9 Months", value: 9 },
    { label: "10 Months", value: 10 },
    { label: "11 Months", value: 11 },
    { label: "12 Months", value: 12 },
  ],
  RFQ_FORM_DATA: 'RFQ_FORM_DATA'
};
